ipfs/rainbow

handlers.go
static/index.html

Handle / path

---

go.mod
keys.go
main.go
setup.go

Keeping track of identities when setting up gateways is a pain.
This allows choosing a single secret for all gateways in a deployment, and then deriving individual keys based on a given index. It also allows painless key rotation.
Once we add bootstrap/peering capabilities, this functionality will be extended and gateways will generate peer IDs for other gateways, look them up on the DHT and peer with them automatically. That is, we will use the DHT for service discovery, skipping manual peering configuration altogether.

Feat: key derivation for libp2p identities

---

.github/workflows/docker.yml
README.md
docker/get-docker-tags.sh

feat(ci): build and publish staging docker images

---

main.go
metrics.go

Copy-pasted some code from Kubo.

feat: export ipfs_p2p metrics like Kubo does

---

rcmgr.go
setup.go

Seems like we need a separate resource manager for the DHT host if it's separate. For now I just reused the limits, but that's obviously not right since that would put the default memory usage at `0.85 * 2` of total memory and `0.5 *2` of total FDs.
Some notes:
- We could separate various flags (connmgr, memory, fd) flags for the new host if we wanted, but either way we need some sensible default percentages to allocate
- For some reason running before #35 does not result in resource manager errors from the accelerated DHT client (perhaps related to smart dialing?), but this change seems needed anyway
Thoughts?

feat: add resource manager for separate DHT libp2p host

---

docs/environment-variables.md
go.mod
handler_test.go
handlers.go
main.go
setup.go

Closes #71.
I made it such that a trustless gateway can also be a subdomain gateway, if you add the domain to both options.

feat: trustless-only mode (RAINBOW_TRUSTLESS_GATEWAY_DOMAINS)

---

docs/environment-variables.md
main.go
setup.go

feat: ipns max cache ttl

---

setup.go

This adds holepunching support to Rainbow, which we care about for the purposes of Rainbow being able to download data from peers behind NATs. This should've been here before but was overlooked because I thought it was in go-libp2p by default😅.
Some notes:
- In order to do holepunching to fetch data from nodes behind NATs the rainbow node must know its public facing address
- This means talking to other nodes and asking them for your address, or just knowing it by setting a public IP address as the listen address
- So if not set via config it's either situational (e.g. based on if you've made some queries that involve downloading data from publicly reachable peers), or requires a shared-host DHT (which is not great for other reasons like excessive resource consumption)
Trying to get this …

fix: enable holepunching

---

.github/workflows/gateway-conformance.yml
handler_test.go
main.go
setup.go

Extracted from #111. Does the following:
- Introduces `dht-routing` flag. Can be `accelerated`, `standard` or `off`. This is personally useful for me locally to disable the accelerated DHT.
- Replaces `routing` with `routing-v1-endpoints` which supports more than one endpoint. Default is cid.contact.
- You can now use DHT Routing and Routing V1 independently (before it was always DHT+cid.contact vs Routing V1).
In the process, I also fixed the typo in the flag `dht-shared-host`, and cleaned up the comma-separated flags to use `StringsSlice`.

feat!: independent dht and routing v1 flags

---

setup.go

This makes sure `rainbow/v1.0.0` shows up in [libp2p identify protocol's agent version field](https://github.com/libp2p/specs/blob/master/identify/README.md#agentversion).
cc @hacdias keep in mind to include this if we initialize more than one libp2p instance host.

fix: libp2p identify agent version

---

docs/environment-variables.md
go.mod
handler_test.go
keys.go
main.go
main_test.go
setup.go
setup_test.go

feat: shared cache for manual peering

---

.github/workflows/docker.yml

Fixes problem documented in https://github.com/ipfs/rainbow/pull/102#issuecomment-2067939704.

ci: trigger docker on release

---

.github/workflows/changelog.yml
CHANGELOG.md
README.md
docs/environment-variables.md

Adds changelog file, better release instructions and CI workflow. Based on https://github.com/ipfs/boxo/pull/398. I will also do this in someguy.
@galargh: I added you as reviewer more for assurance, but is not required. I will merge this in a few hours if I haven't gotten a review and try it out with v1.1.0.

ci: add changelog check

---

CHANGELOG.md
docs/environment-variables.md
go.mod
keys.go
main.go
setup.go
setup_routing.go
setup_test.go

Closes #109. This PR adds seed-based automatic peering. This works by either leveraging the already-running DHT (if DHT is enabled with shared host), or running a parallel DHT with the main host only for peer routing.
I've added tests that you can run on your machine, but disabled on the CI. The time it takes to connect can vary and I thought it could be a bit flaky to run in the CI. In addition, it would maybe pollute the Amino DHT with all ephemeral peers that are created in each test.
Depends on https://github.com/ipfs/rainbow/pull/114.
Closes #27

feat: seed-based automatic peering

---

CHANGELOG.md
setup.go

When introducing #114, we enabled provider announcements for the Bitswap server when the peering shared cache is enabled. That is not needed, and only adds additional work load to the Rainbow node. Here we disable it (it's true by default).

fix: disable bitswap provider announcements

---

CHANGELOG.md
docs/environment-variables.md
main.go
setup.go
setup_bitswap.go
setup_test.go
version.json

@aschmahmann as discussed, this restores bitswap setup we had in v1.0.0 where only the client is initialized by default.
If this looks ok, we can ship this as v1.2.2 and deploy to our infra.

fix: default to bitswap-client-only

---

.github/workflows/docker.yml
.github/workflows/releaser.yml

Using a custom GItHub token in releaser was introduced in https://github.com/ipdxco/unified-github-workflows/releases/tag/v1.0.2
I set up a custom fine-grained PAT with contents write access only to this repository. The token is owned by web3-bot and valid for 1 year.
By using custom PAT we should be able to react to tag push events in the docker publish workflow again.
Testing -> we're going to oversee the next release to make 100% sure the automation works as expected.
❓ Are there any other repos where you'd like us to introduce a change like this one?

refactor(ci): automate docker releases on tag pushes

---

CHANGELOG.md
main.go

This is an updated version of #59 that closes #128 
While we have holepunching support and might not need public listen addresses having them will make things more robust since we can rely on dialback behavior rather than holepunching. While we can listen on the default addresses having configurability here makes it easier for us to enable limited firewall rules.
Note: we could add announce addresses as well if we wanted, at the moment I've left it out to reduce complexity around announce vs append-announce and since I don't have an immediate need for it (e.g. not announcing DNS names). If others want this we could certainly add it though.

cli: libp2p listen addresses

---

CHANGELOG.md
metrics.go

fix(metrics): more duration histogram buckets

---

CHANGELOG.md
version.go

The tagged release version should match the contents of version.json, so embed the version.json file and add the release version from it to the output from `--version`.
Output:
```shell
> docker run --rm -it 3dc6e920ed8d --version
rainbow version v1.3.0 2024-06-18-7d805fd-dirty                               
rainbow version v1.3.0 2024-06-18-7d805fd-dirty
```
Fixes #145

fix: --version flag includes release version

---

CHANGELOG.md
docs/headers.md
go.mod
go.sum
handler_test.go
handlers.go
main.go
main_test.go
metrics.go
setup.go

Adds a header (protected by the Authorization header) for skipping the blockcache to better aid debugging.
Based off of #143

feat: add header for skipping the blockcache

---

CHANGELOG.md
README.md
handlers.go
main.go

Adds an HTTP API for logging so it can be dynamically modified at runtime, also adds an API for listing all logging subsystems.

feat: add logging http api

---

CHANGELOG.md
version.json

Releasing as v1.6.0 because of go version bump + dependency changes (fixes) are significant.

chore: release v1.6.0

---

README.md
docs/environment-variables.md
docs/tracing.md

This PR added `docs/tracing.md` with working example of per-request tracing.

docs: dedicated tracing.md

---

version.json

New version with updated boxo v0.24.1

Create new version

---

CHANGELOG.md
docs/headers.md
handler_test.go
handlers.go

We previously just didn't honor headers that required authorization but didn't provide it, this errors making things more explicit and less error prone. @gammazero just ran into some confusion here and it seems like being more explicit here could be helpful.
WDYT @lidel?

Error instead of dropping unauthorized headers

---

CHANGELOG.md
go.mod
go.sum
handler_test.go
setup_bitswap.go

This builds off of https://github.com/ipfs/boxo/pull/641 and at the moment has two notable changes from the current setup:
1. The limit of in process lookups was raised from 6 to 100
2. The limit on provider records to lookup was removed
Without some experimentation it's hard to tell what these numbers should be or what other sorts of heuristics we might want to use here. I don't think the ones we have are optimal, but for now figured we'd see if mostly tweaking the numbers helps at all. It's also not clear that we'd want both DHT and IPNI lookups to be rate-limited in the same way and right now they're joined together.
We should try this out on a staging branch and see what the impact looks like.

feat: increase routing limits

---

CHANGELOG.md
docs/environment-variables.md
go.mod
main.go
main_test.go
setup.go
setup_test.go

Adds the ability to configure custom DNSLink resolvers

feat: custom dnslink resolvers

---

CHANGELOG.md
docs/environment-variables.md
setup.go

This is rainbow version of https://github.com/ipfs/kubo/pull/10655, because Rainbow has own defaults
TLDR reason:
https://github.com/ipfs/boxo/issues/771#issuecomment-2573189494
> Ref. https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#2025-07-01:
> ![image](https://github.com/user-attachments/assets/4171a1f0-6918-4b7e-9496-233c2aded13d)

fix: update default DNSLink resolvers

---

README.md

Seems readme does not mention automatic GC

docs(readme): automatic gc

---

docs/environment-variables.md

Closes #254.
Adds Documentation for the HTTP retrieval environment variables in `docs/environment-variables.md`
```
ROUTING_IGNORE_PROVIDERS
RAINBOW_HTTP_RETRIEVAL_ENABLE
RAINBOW_HTTP_RETRIEVAL_ALLOWLIST
RAINBOW_HTTP_RETRIEVAL_WORKERS 
```

docs(env-variables): Add HTTP retrieval environment variables documentation.

---

setup_bitswap.go

Setting to the same value we already use for libp2p:
https://github.com/ipfs/rainbow/blob/1bf59f710821432bbb28c5ffe98d4028087e5c7e/setup_routing.go#L82
This makes is easier to track which specific rainbow build/release is responsible for requests.
We need this, because Kubo and Rainbow may use the same boxo, but initialize client with slightly different config (Ref. https://github.com/ipfs/kubo/pull/10772)

fix: set User-Agent for HTTP retrieval client
